# Generated by Django 3.2.4 on 2021-07-02 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('passCode', models.CharField(blank=True, max_length=20, null=True)),
                ('organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('organisationLogo', models.CharField(blank=True, max_length=100, null=True)),
                ('instruction', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('startDate', models.DateTimeField(default=datetime.datetime(2021, 7, 2, 18, 17, 25, 338976))),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('question', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionNo', models.IntegerField(max_length=2)),
                ('question', models.TextField()),
                ('maxScore', models.IntegerField(max_length=2)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
