# Generated by Django 3.2.4 on 2021-08-02 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='maxScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizQuestions', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 12, 56, 42, 262022)),
        ),
    ]
