# Generated by Django 3.2.4 on 2021-08-20 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210802_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 13, 32, 52, 724261)),
        ),
    ]
