# Generated by Django 3.2.4 on 2021-08-23 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 9, 30, 24, 22278)),
        ),
        migrations.CreateModel(
            name='CandidateData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidateName', models.TextField()),
                ('candidateNumber', models.TextField()),
                ('passCode', models.FileField(upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.FileField(upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('candidateDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.candidatedata')),
                ('questionsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions')),
            ],
        ),
    ]
