# Generated by Django 3.1.7 on 2021-05-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=3, max_digits=11)),
                ('purchases', models.IntegerField(default=0)),
                ('lessons', models.IntegerField(default=0)),
                ('isPublished', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replies', to='courses.comments')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('courseSlug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='courses.courses', to_field='slug')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='lessonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comment', to='courses.lessons'),
        ),
        migrations.AddField(
            model_name='comments',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
