# Generated by Django 3.1.7 on 2021-04-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210422_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='lessons',
            field=models.IntegerField(default=0),
        ),
    ]
