# Generated by Django 3.2.4 on 2021-06-24 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20210617_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isPurchased', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to='courses.courses')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
