# Generated by Django 3.1.7 on 2021-04-26 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210422_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.courses')),
            ],
        ),
    ]
